import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: "html",
      value:
        '<div style="margin: 10px 0; font-size: 1.1em; color: #888;">Getting Started</div>',
      defaultStyle: false,
    },

    "intro",

    {
      type: "html",
      value:
        '<div style="margin: 10px 0; font-size: 1.1em; color: #888;">Installation</div>',
      defaultStyle: false,
    },
    "installation/download",
    "installation/setup",
    "installation/configure",
    "installation/customize",

    {
      type: "html",
      value:
        '<div style="margin: 10px 0; font-size: 1.1em; color: #888;">Miscellaneous</div>',
      defaultStyle: false,
    },
    "contribute",
    {
      type: "link",
      label: "Free Access Key",
      href: "https://admin.sista.ai/applications",
    },
    {
      type: "link",
      label: "Open Source",
      href: "https://github.com/sista-ai",
    },
		{
      type: "link",
      label: "Privacy",
      href: "https://smart.sista.ai/privacy.html?utm_source=sista_docs&utm_medium=sider_link&utm_campaign=privacy_policy",
    },
    {
      type: "link",
      label: "About Us",
      href: "https://smart.sista.ai/about.html?utm_source=sista_docs&utm_medium=sider_link&utm_campaign=about_sista_ai",
    },
  ],
};

export default sidebars;
