import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: "html",
      value:
        '<div style="margin: 10px 0; font-size: 1.1em; color: #888;">Getting Started</div>',
      defaultStyle: false,
    },

    "intro",

    {
      type: "html",
      value:
        '<div style="margin: 10px 0; font-size: 1.1em; color: #888;">Installation</div>',
      defaultStyle: false,
    },
    "installation/download",
    "installation/setup",
    "installation/configure",
    "installation/customize",

    {
      type: "html",
      value:
        '<div style="margin: 10px 0; font-size: 1.1em; color: #888;">Miscellaneous</div>',
      defaultStyle: false,
    },
    "contribute",
  ],
};

export default sidebars;
